name: viz_tutorial
channels:
  - conda-forge
dependencies:
  - pip
  - jupyterlab
  - matplotlib
  - ipympl
  - seaborn
  - holoviews
  - pyvista
  - plotly
  - streamlit
  - dash
  - xarray
  - datashader
